- name: Deploy Calculator Container
  hosts: myhosts

  tasks:

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: siddheshhh/calculator-app
        tag: "1.0"
        source: pull

    - name: Stop existing container
      community.docker.docker_container:
        name: calculator-container
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: calculator-container
        image: siddheshhh/calculator-app:1.0
        state: started
        recreate: true
        tty: true
        interactive: true
